### ISSUE TITLE
consider this module

### ISSUE THREAD

**Issue by sunnysideup** [xini/silverstripe-international-phone-number-field#10]
Hi Florian,

Is this of interest to you:  https://github.com/sunnysideup/silverstripe-phone_field ? You may want to list it in your README.md?  Well, if you think it is helpful.  The module basically creates a PhoneField in the database (Varchar with some extras). 

I just had a look at this module - not in detail - but looks great!

**Comment by xini** [comment]
Thanks for the info. I'll have a look.

**Comment by xini** [comment]
I have taken this on board and implemented a database field for this in version 4.0.0. See readme for more info.
