### ISSUE TITLE
Setting initial_country does not work

### ISSUE THREAD

**Issue by tomzi** [xini/silverstripe-international-phone-number-field#4]
**Hello**
My website uses https and i try to set initial_country to something else than 'auto' like 'BE' or 'FR' but that does not work.
Do you have a solution for that ?

Thanks a lot!
Thomas

**Comment by xini** [comment]
Hi @tomzi I have just released version 2.0.2 which fixes this issue. (you had to use lower case country codes before this fix.) Cheers
