### ISSUE TITLE
Enhancement: template formatter for phone number

### ISSUE THREAD

**Issue by wernerkrauss** [xini/silverstripe-international-phone-number-field#5]
It would be nice to have some formatters available which I could use in the templates, like

    <a href="$Tel.URI">$Tel.Nice</a>

**Comment by xini** [comment]
Hi Werner,

Yes, this sounds interesting. At the moment, the module only provides a form field storing the data in a text field. Happy to accept a PR to add a DBField with these formatters.

Cheers

**Comment by xini** [comment]
This has now been implemented in version 4.0.0. See readme for formatting options.
