### ISSUE TITLE
background images path uses resources not _resources

### ISSUE THREAD

**Issue by ivoba** [xini/silverstripe-international-phone-number-field#8]
Seems the resources path has changed in SS4.4:

> New projects will be preset to _resources. This will avoid potential conflict with SiteTree URL Segments.

from: https://docs.silverstripe.org/en/4/changelogs/4.4.0/

Since the module uses hard-coded `resources` it breaks in SS4.4 projects with default resources-dir which is `_resources`.

**Comment by xini** [comment]
Thanks. I'll have a look into this asap.

**Comment by xini** [comment]
This is now fixed in [release 3.0.3](https://github.com/xini/silverstripe-international-phone-number-field/releases/tag/3.0.3)
